#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: scripts/bag-mode-primitive-matrix-scaffold.sh --output-dir DIR
   or: scripts/bag-mode-primitive-matrix-scaffold.sh DIR

Creates a non-mutating starter directory for the #29 Bag Mode primitive matrix.
The generated manifest intentionally contains TODO rows so it cannot pass the
matrix verifier until each row is replaced with real evidence, a concrete N/A
reason, or a concrete deferred reason.
USAGE
}

OUTPUT_DIR=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-dir)
            if [[ $# -lt 2 ]]; then
                echo "--output-dir requires a value" >&2
                exit 64
            fi
            OUTPUT_DIR="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 64
            ;;
        *)
            if [[ -n "$OUTPUT_DIR" ]]; then
                echo "Output directory provided more than once" >&2
                usage >&2
                exit 64
            fi
            OUTPUT_DIR="$1"
            shift
            ;;
    esac
done

if [[ -z "$OUTPUT_DIR" ]]; then
    usage >&2
    exit 64
fi

if [[ -e "$OUTPUT_DIR" && ! -d "$OUTPUT_DIR" ]]; then
    echo "Output path exists but is not a directory: $OUTPUT_DIR" >&2
    exit 73
fi

if [[ -e "$OUTPUT_DIR" ]]; then
    if [[ -n "$(find "$OUTPUT_DIR" -mindepth 1 -maxdepth 1 2>/dev/null)" ]]; then
        echo "Output directory is not empty: $OUTPUT_DIR" >&2
        exit 73
    fi
fi

mkdir -p "$OUTPUT_DIR"

write_manifest_row() {
    local case_id="$1"
    printf '%s\tTODO\t\tReplace TODO with evidence, n/a, or deferred before verification\n' "$case_id"
}

cat >"$OUTPUT_DIR/matrix-manifest.tsv" <<'EOF'
caseId	status	evidenceDir	naReason
EOF

{
    write_manifest_row "apple-silicon-ac-internal-open-normal"
    write_manifest_row "apple-silicon-ac-internal-closed-normal"
    write_manifest_row "apple-silicon-ac-internal-reopen-normal"
    write_manifest_row "apple-silicon-battery-internal-open-normal"
    write_manifest_row "apple-silicon-battery-internal-closed-normal"
    write_manifest_row "apple-silicon-battery-internal-reopen-normal"
    write_manifest_row "apple-silicon-ac-external-display-normal"
    write_manifest_row "apple-silicon-battery-external-display-normal"
    write_manifest_row "apple-silicon-ac-no-external-display-normal"
    write_manifest_row "apple-silicon-battery-no-external-display-normal"
    write_manifest_row "apple-silicon-ac-internal-app-quit"
    write_manifest_row "apple-silicon-battery-internal-app-quit"
    write_manifest_row "apple-silicon-ac-internal-crash"
    write_manifest_row "apple-silicon-battery-internal-crash"
    write_manifest_row "apple-silicon-ac-internal-reboot-held"
    write_manifest_row "apple-silicon-battery-internal-reboot-held"
    write_manifest_row "macos-13-host"
    write_manifest_row "macos-14-host"
    write_manifest_row "macos-15plus-host"
    write_manifest_row "intel-host"
    printf '%s\tdeferred\t\tBlocked until #27 produces a signed helper prototype\n' "helper-restart-after-27"
    printf '%s\tdeferred\t\tBlocked until #27 produces a signed helper prototype\n' "helper-upgrade-after-27"
} >>"$OUTPUT_DIR/matrix-manifest.tsv"

cat >"$OUTPUT_DIR/README.md" <<'EOF'
# Bag Mode Primitive Matrix Scaffold

This directory is a starter scaffold for issue #29. It is not evidence.

The manifest intentionally starts with `TODO` statuses. Before attaching a
matrix to #29, replace every `TODO` row with one of:

- `evidence` plus an evidence directory generated by `scripts/bag-mode-primitive-validation.sh`
- `n/a` plus a concrete physical availability reason
- `deferred` plus a concrete blocker, such as helper-only lifecycle rows waiting on #27

Run the verifier before attaching the matrix:

```sh
scripts/bag-mode-primitive-matrix-verify.sh --manifest <this-dir>/matrix-manifest.tsv
```

Verifier success only means the manifest and evidence package are structurally
complete. It does not mean the primitive passed the hardware matrix.

For non-reboot evidence rows, use:

```sh
sudo scripts/bag-mode-primitive-validation.sh \
  --output-dir <this-dir>/<case-id> \
  --case-id <case-id> \
  --apply \
  --i-understand-this-changes-power-settings
```

For reboot-held evidence rows, add `--reboot-held`, follow
`ROLLBACK_REQUIRED.txt` after restart, capture `post-reboot/`, roll back the
captured prior value, and capture `after-rollback/`.
EOF

cat >"$OUTPUT_DIR/scaffold-config.txt" <<EOF
scaffoldFormat=bag-mode-primitive-matrix-scaffold-v1
createdAtUtc=$(date -u +%Y-%m-%dT%H:%M:%SZ)
metadataRedacted=true
manifest=matrix-manifest.tsv
verifier=scripts/bag-mode-primitive-matrix-verify.sh --manifest $OUTPUT_DIR/matrix-manifest.tsv
EOF

echo "Bag Mode primitive matrix scaffold written to $OUTPUT_DIR"
